web_server:
  bind: 0.0.0.0
  port: 3539
  
schedules:
  - tasks: '*'
    interval:
      minutes: 30
  
templates:
  tv:
    regexp:
      reject:
        - x265: {from: title}
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p
      tv:
        - The Mandalorian
        - Mr Robot

    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "123456"

tasks:
  eztvrss:
    rss: https://eztv.ag/ezrss.xml
    template: tv
    priority: 2
    